version: '3'

services:
  dbStock:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3309:3306"
    volumes:
      - dbStock-data:/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9091:80"
    environment:
      PMA_HOST: dbStock
      MYSQL_ROOT_PASSWORD: yourpassword

  gestion:
    container_name: GStock
    # image: perce26/entrersortie:la_capitale
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2020:3333"
    environment:
      # NODE_ENV: production
      dbStock_CONNECTION: mysql
      MYSQL_HOST: dbStock
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: stock-db

volumes:
  dbStock-data:
