version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3301:3306"
    volumes:
      - db-data:/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: yourpassword

  gstock:
    container_name: gstock_backend
    # image: perce26/entrersortie:la_capitale_restaurant
    build:
      context: ./dsh
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:3333"
    environment:
      # NODE_ENV: production
      DB_CONNECTION: mysql
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: stock-db

  gstocktggrossiste:
    container_name: gestion_stock_tggrossiste
    # image: perce26/entrersortie:gestion_restaurant
    build:
      context: ./tggrossiste
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8877:3333"
    environment:
      # NODE_ENV: production
      DB_CONNECTION: mysql
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: stock-db-tggrossiste

  gstockn2a:
    container_name: gestion_stock_n2a
    # image: perce26/entrersortie:gestion_restaurant
    build:
      context: ./n2a
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8866:3333"
    environment:
      # NODE_ENV: production
      DB_CONNECTION: mysql
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: stock-db-n2a

  gstockdshfood:
    container_name: gestion_stock_dshfood
    # image: perce26/entrersortie:gestion_restaurant
    build:
      context: ./dshfood
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8855:3333"
    environment:
      # NODE_ENV: production
      DB_CONNECTION: mysql
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: stock-db-dshfood

  # la capitale backend
  la_capitale:
    container_name: la_capitale
    # image: perce26/entrersortie:gestion_restaurant
    build:
      context: ./capitale
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    environment:
      # NODE_ENV: production
      DB_CONNECTION: mysql
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: la-capitale # la capitale backend
  imageapp:
    container_name: imageapp
    # image: perce26/entrersortie:gestion_restaurant
    build:
      context: ./imageApp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8844:3333"
    environment:
      # NODE_ENV: production
      DB_CONNECTION: mysql
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: imageapp-db
    volumes:
      - uploads-volume:/public/uploads

volumes:
  db-data:
  uploads-volume:
