version: '3'

services:
  gestion:
    container_name: GStock
    # image: perce26/entrersortie:la_capitale
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2020:3333"

