version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3303:3306"  # Change the host port to the desired MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stock-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    command: "--skip-networking=0 --bind-address=::"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    ports:
      - "8081:80"  # Change the host port to the desired phpMyAdmin port
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password

  gestion:
    container_name: gestion_stock
    # image: perce26/entrersortie:gestion_restaurant
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6666:3333"
    environment:
      # NODE_ENV: production
      DB_CONNECTION: mysql
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: stock-db
