version: '3'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - db-data:/mysqldb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8081:80"  # Change the host port to the desired phpMyAdmin port
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password

  gestion:
    container_name: gestion_stock
    # image: perce26/entrersortie:gestion_restaurant
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7777:3333"
    environment:
      # NODE_ENV: production
      DB_CONNECTION: mysql
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: stock-db

volumes:
  db-data:
